### ISSUE TITLE
Init project

### ISSUE THREAD

**Issue by zaikin-andrew** [BestMood-Tech/Hirefy-client#1]
- use angular cli 
- implement materinal angular
- set up CI via CircleCI and run base tests

**Comment by sermolenko-bmt** [comment]
0.5 - 1 hour

**Comment by sermolenko-bmt** [comment]
via Hubstaff
User: Semyon Ermolenko

Project: Hirefy-client - https://app.hubstaff.com/projects/300615
Date Range: 10/16/17 - 10/16/17
Work session total: 0:22:29

Grand total: 0:22:29
