### ISSUE TITLE
Applicant data – Total, Favourites, Rejected

### ISSUE THREAD

**Issue by zaikin-andrew** [BestMood-Tech/Hirefy-client#100]
Display total applicants, favourites and rejected numbers in Job header for all users in both the Customer Account and the Hirefy(admin) Account.
**Note that the screen grabs I included have the US spelling of Favorites... but we'd like to stick with the English spelling Favourites per the rest of the app**

![image](https://user-images.githubusercontent.com/7475399/36641963-6530f0c2-1a49-11e8-9f8b-1fd8c3a08356.png)
![image](https://user-images.githubusercontent.com/7475399/36641967-6c49555c-1a49-11e8-8a3f-b49573c3175d.png)

Applicant numbers should update across all job tiles when new applicants are added manually by Hirefy
Favourites should update live across all job tiles as Customers selects favourites. Rejected should update live across all job tiles as Customer rejects applicants.

**Comment by sermolenko-bmt** [comment]
via Hubstaff
User: Semyon Ermolenko

Project: Hirefy-client - https://app.hubstaff.com/projects/300615
Date Range: 02/26/18 - 02/26/18
Work session total: 1:59:35

Grand total: 1:59:35
