### ISSUE TITLE
Star Ratings For All Candidates

### ISSUE THREAD

**Issue by zaikin-andrew** [BestMood-Tech/Hirefy-client#101]
All Candidate Profiles and Results Tiles are to have a 5-star rating system.
The star rating can be viewed / edited by any Customer logon. i.e. if a Customer has multiple users, they can all see the star rating and can alter it.
The star rating should be able to be edited from either the Results page, or within the Candidate Profile.
The stars should automatically select in sequential order... I.e. If the user chooses to rate them as 3 stars, the system should automatically highlight stars 1-3... not just star 3.
The star ratings should be accurate **to half a star**. i.e. User can rate a candidate **3.5 stars**.
Hirefy administrators should be able to see the star rating within the candidate profile, but not on the results table as there is enough data in the results tiles already for Hirefy users.
![image](https://user-images.githubusercontent.com/7475399/36641999-3cf95b7a-1a4a-11e8-8dcf-024fa8cd777c.png)
![image](https://user-images.githubusercontent.com/7475399/36642000-40faacc4-1a4a-11e8-84ab-d210ebc7f45a.png)

The behaviour I anticipate (based on what we've seem with the UAV job) is:
- customer shortlists favourites (some customers will reject all the rest, but most won't)
- the the customer will rank their favourites using the stars

So I'd expect none of the favourites that they star rank will get zero... they should all get ranked between 3-5 mostly.

In the end (at some stage in the future) we will want the customer to be able to filter their favourites list by the star ratings, not just the percentage match.

**Comment by oskvortsov-bmt** [comment]
via Hubstaff
User: Oleg Skvortsov

Project: Hirefy-client - https://app.hubstaff.com/projects/300615
Date Range: 02/26/18 - 02/26/18
Work session total: 5:05:57

Grand total: 5:05:57

**Comment by oskvortsov-bmt** [comment]
via Hubstaff
User: Oleg Skvortsov

Project: Hirefy-client - https://app.hubstaff.com/projects/300615
Date Range: 02/27/18 - 02/27/18
Work session total: 1:57:59

Grand total: 7:03:56
