### ISSUE TITLE
Newly Added Applicants Highlighted in Results

### ISSUE THREAD

**Issue by zaikin-andrew** [BestMood-Tech/Hirefy-client#102]
New applicants that have been uploaded should be highlighted within the Results table for all Customer Account users using a blue band.
The new applicant highlight should stay in place until one of the following conditions is met:
- the Customer Account user opens the new candidates profile.
- the Customer Account user has logged in twice and viewed the Results list.
After the Customer Account user has logged in twice and viewed the results list, even if they still haven’t viewed the new Candidate Profile, the highlight can be removed.
This function should apply for each individual user in the Customer Account. The blue to be used for the New applicant highlight band is: #00B8D9.

![image](https://user-images.githubusercontent.com/7475399/36642087-24450682-1a4b-11e8-9f0e-4d11755301be.png)

the Total, Favourtes, Rejected numbers being listed on the job headers: can we also please get the Total applicants number listed in Blue when there are new applicants added. So the conditions should be the same as for the blue notification sash on results indicating that there are new applicants... any time there are new applicants in the system the Total Applicants indicator should also be a blue number. Use the same blue colour specified.

**Comment by oskvortsov-bmt** [comment]
via Hubstaff
User: Oleg Skvortsov

Project: Hirefy-client - https://app.hubstaff.com/projects/300615
Date Range: 02/27/18 - 02/27/18
Work session total: 1:29:40

Grand total: 1:29:40

**Comment by oskvortsov-bmt** [comment]
via Hubstaff
User: Oleg Skvortsov

Project: Hirefy-client - https://app.hubstaff.com/projects/300615
Date Range: 02/28/18 - 02/28/18
Work session total: 4:30:25

Grand total: 6:00:05
