### ISSUE TITLE
Ability To Add Notes To Candidates

### ISSUE THREAD

**Issue by zaikin-andrew** [BestMood-Tech/Hirefy-client#103]
The notes tab should default to the closed position.
It should start in line  **at the top** of the Candidate Profile header but remained pinned in that relative location on the screen as the user scrolls, so that the tab scrolls up and down the page as well.
When clicked the tab should pop out to a notes dialogue box similar to the one illustrated.
The entire notes dialogue box should scroll in place with the screen per the instruction above regarding the Notes tab.
When clicked again the Note tab should close the dialogue box.
Notes can be added in a window the user can type in, and then click add note.

The note should appear similar in style to a text message, like the illustration, and should be marked with the user who added the note and the date it was added.
The entire Notes dialogue box should be able to expand down the page as required for all notes to be visible (no scrolling if it can be avoided).
Notes can be edited by the user who created them, by clicking on them.
Notes are not able to be edited by any other user.
All notes should be visible to the Hirefy administrators in the Candidate profiles as well.

The Notes tab and expanded dialogue box should be pinned **at the top** of the Candidate Profile header, **instead of at the top of their answers**... it should still be pinned in place and scroll with the screen. Adding it towards the top of the page instead of half way down will allow more room for notes if required.

![image](https://user-images.githubusercontent.com/7475399/36642121-9d2f224e-1a4b-11e8-97cb-18268b67fc2e.png)
![image](https://user-images.githubusercontent.com/7475399/36642124-a19a5696-1a4b-11e8-84f3-d0b91fb7cd8d.png)

**Comment by sermolenko-bmt** [comment]
via Hubstaff
User: Semyon Ermolenko

Project: Hirefy-client - https://app.hubstaff.com/projects/300615
Date Range: 02/26/18 - 02/26/18
Work session total: 0:27:23

Grand total: 0:27:23

**Comment by sermolenko-bmt** [comment]
via Hubstaff
User: Semyon Ermolenko

Project: Hirefy-client - https://app.hubstaff.com/projects/300615
Date Range: 02/27/18 - 02/27/18
Work session total: 3:45:45

Grand total: 4:13:08

**Comment by sermolenko-bmt** [comment]
via Hubstaff
User: Semyon Ermolenko

Project: Hirefy-client - https://app.hubstaff.com/projects/300615
Date Range: 02/28/18 - 02/28/18
Work session total: 2:59:12

Grand total: 7:12:20
