### ISSUE TITLE
Integration with API

### ISSUE THREAD

**Issue by zaikin-andrew** [BestMood-Tech/Hirefy-client#11]
- set up integration with backend when it will be completed

Est. 3-4hrs.

**Comment by sermolenko-bmt** [comment]
via Hubstaff
User: Semyon Ermolenko

Project: Hirefy-client - https://app.hubstaff.com/projects/300615
Date Range: 10/24/17 - 10/24/17
Work session total: 0:14:41

Grand total: 0:14:41

**Comment by sermolenko-bmt** [comment]
via Hubstaff
User: Semyon Ermolenko

Project: Hirefy-client - https://app.hubstaff.com/projects/300615
Date Range: 10/25/17 - 10/25/17
Work session total: 1:08:54

Grand total: 1:23:35

**Comment by sermolenko-bmt** [comment]
via Hubstaff
User: Semyon Ermolenko

Project: Hirefy-client - https://app.hubstaff.com/projects/300615
Date Range: 10/26/17 - 10/26/17
Work session total: 0:18:06

Grand total: 1:41:41
