### ISSUE TITLE
New functional for the Customer and Job Scoring Editor pages

### ISSUE THREAD

**Issue by zaikin-andrew** [BestMood-Tech/Hirefy-client#19]
A functional change we would like to make - which is a change to the scope - we realised that if we stuff up creating the JSON file, we have no way to edit / delete jobs, apart from out of the db itself.

We'd also like the job numbers to be automatically assigned in the system, and displayed for the job rather than manually adding a Job ID to the JSON file.

On the Customer homepage, instead of being able to upload a JSON file, can we have the ability to 'create job' which let's us enter a name for the job, gives us a job id, and created all the job options....

From there we can go to 'Edit Scoring' and upload the JSON file. Also an option to delete it if needed. It would be good if there is a 'are you sure' prompt once you hit the delete button as well, to save anyone accidentally deleting data.

This will mean we assign proper job numebr per job, and we have the ability to delete and restart the JSON for that job if we stuff it up.

[Mockups](https://app.moqups.com/NickHirefy/sah0jrZZnC/view)

Estimate it please.

**Comment by sermolenko-bmt** [comment]
2 - 4 hour

**Comment by sermolenko-bmt** [comment]
via Hubstaff
User: Semyon Ermolenko

Project: Hirefy-client - https://app.hubstaff.com/projects/300615
Date Range: 11/01/17 - 11/01/17
Work session total: 2:46:11

Grand total: 2:46:11

**Comment by sermolenko-bmt** [comment]
via Hubstaff
User: Semyon Ermolenko

Project: Hirefy-client - https://app.hubstaff.com/projects/300615
Date Range: 11/02/17 - 11/02/17
Work session total: 1:14:19

Grand total: 4:00:30
