### ISSUE TITLE
Login page

### ISSUE THREAD

**Issue by zaikin-andrew** [BestMood-Tech/Hirefy-client#2]
- add layout and base styles
- add auth logic
- add guard

**Comment by sermolenko-bmt** [comment]
2 - 4 hour

**Comment by sermolenko-bmt** [comment]
via Hubstaff
User: Semyon Ermolenko

Project: Hirefy-client - https://app.hubstaff.com/projects/300615
Date Range: 10/17/17 - 10/17/17
Work session total: 0:43:48

Grand total: 0:43:48

**Comment by sermolenko-bmt** [comment]
via Hubstaff
User: Semyon Ermolenko

Project: Hirefy-client - https://app.hubstaff.com/projects/300615
Date Range: 10/18/17 - 10/18/17
Work session total: 2:25:04

Grand total: 3:08:52
