### ISSUE TITLE
% of maximum possible score

### ISSUE THREAD

**Issue by zaikin-andrew** [BestMood-Tech/Hirefy-client#27]
> On the Job Report page, can we get a column added for % of maximum possible score? i.e. if the app can calculate the maximum possible score a candidate can get on a job, per the scoring rules we set up, and display a percentage of total score for each applicant on the Job Report page.

- add a column for %
- add an ability to sort by this column

**Comment by sermolenko-bmt** [comment]
2-4 hour

**Comment by sermolenko-bmt** [comment]
via Hubstaff
User: Semyon Ermolenko

Project: Hirefy-client - https://app.hubstaff.com/projects/300615
Date Range: 11/16/17 - 11/16/17
Work session total: 2:22:41

Grand total: 2:22:41

**Comment by sermolenko-bmt** [comment]
via Hubstaff
User: Semyon Ermolenko

Project: Hirefy-client - https://app.hubstaff.com/projects/300615
Date Range: 11/18/17 - 11/18/17
Work session total: 0:12:06

Grand total: 2:34:47
