### ISSUE TITLE
Customers page

### ISSUE THREAD

**Issue by zaikin-andrew** [BestMood-Tech/Hirefy-client#3]
- add layout and base styles
- add form

**Comment by sermolenko-bmt** [comment]
1 -2 hour

**Comment by sermolenko-bmt** [comment]
via Hubstaff
User: Semyon Ermolenko

Project: Hirefy-client - https://app.hubstaff.com/projects/300615
Date Range: 10/22/17 - 10/22/17
Work session total: 1:48:40

Grand total: 1:48:40
