### ISSUE TITLE
Candidate Profile Page

### ISSUE THREAD

**Issue by zaikin-andrew** [BestMood-Tech/Hirefy-client#31]
https://app.moqups.com/NickHirefy/sah0jrZZnC/view/page/aee3b9381
# Candidate Profile Page

Each candidate who has survey information uploaded should have a 'Candidate Profile' generated, that can be accessed by clicking the candidate name on the Job Report page.

The Candidate Profile will contain basic information such as name, the job, rank, score, and a bar showing overall percentage match for the role.

The candidate responses to all questions will be set out in the profile for manual review by the customer. Info can be taken from the JSON file and uploaded CSV responses at this stage.

The Candidate Profile will also contain bar graphs illustrating percentage match to three criteria - Basic Requirements, Skills Match and Cultural Fit.

Skills Match = percentage of the max possible score for the "rank yourself out of 0 - 3 for these required skills"
Cultural Fit = percentage of max possible score for the "what is most important to you in a new job, rank in order" responses.
Basic Requirements = percentage of max possible score for all other responses including anything on location, residency status, education, salary etc.

Because the question details and order will change each time, is there a way we can manually identify the three different criteria in JSON file?

Also, note the re new percentages / bar graphs for Basic Requirements, Skills, and Cultural Fit.... 
Cultural Fit percentage score should just come from the 'Preferences' answers in Q10 above
Skills percentage score should just come from the 'Skills' answers in Q11 above
Basic Requirements score should come from everything else we're scoring
We'll be expanding the questions we ask about Skills and Preferences (Cultural Fit) as we go, so this is just a starting point.

@sermolenko-bmt what do you think?

**Comment by sermolenko-bmt** [comment]
4 - 6 hours

**Comment by sermolenko-bmt** [comment]
via Hubstaff
User: Semyon Ermolenko

Project: Hirefy-client - https://app.hubstaff.com/projects/300615
Date Range: 11/20/17 - 11/20/17
Work session total: 1:12:24

Grand total: 1:12:24

**Comment by sermolenko-bmt** [comment]
via Hubstaff
User: Semyon Ermolenko

Project: Hirefy-client - https://app.hubstaff.com/projects/300615
Date Range: 11/21/17 - 11/21/17
Work session total: 2:04:39

Grand total: 3:17:03

**Comment by sermolenko-bmt** [comment]
via Hubstaff
User: Semyon Ermolenko

Project: Hirefy-client - https://app.hubstaff.com/projects/300615
Date Range: 11/22/17 - 11/22/17
Work session total: 2:20:19

Grand total: 5:37:22

**Comment by sermolenko-bmt** [comment]
via Hubstaff
User: Semyon Ermolenko

Project: Hirefy-client - https://app.hubstaff.com/projects/300615
Date Range: 11/23/17 - 11/23/17
Work session total: 0:20:15

Grand total: 5:57:37
