### ISSUE TITLE
Default 'na' Category Tag in JSON

### ISSUE THREAD

**Issue by zaikin-andrew** [BestMood-Tech/Hirefy-client#35]
Currently, the default category tag is 'basic'. We'd like the ability to add/remove 'basic' from certain questions. Can we please have the default category set as 'NA' (not applicable or null), and the ability to add ‘basic’ as a category in the JSON to specific questions.
![image](https://user-images.githubusercontent.com/7475399/33309734-3e3d36a6-d430-11e7-86c6-66c54793216b.png)

**Comment by sermolenko-bmt** [comment]
1 - 2 hour

**Comment by sermolenko-bmt** [comment]
via Hubstaff
User: Semyon Ermolenko

Project: Hirefy-client - https://app.hubstaff.com/projects/300615
Date Range: 11/29/17 - 11/29/17
Work session total: 0:23:45

Grand total: 0:23:45
