### ISSUE TITLE
Delete Buttons

### ISSUE THREAD

**Issue by zaikin-andrew** [BestMood-Tech/Hirefy-client#36]
Per the updated wireframe, we’d like to get delete buttons added to the Jobs, and Results screens.

The delete button on the Jobs page should delete the entire job record, JSON data and csv results uploaded to from the db. Naturally, we’d like an “Are you sure – OK / Cancel” dialogue from this delete button.

![image](https://user-images.githubusercontent.com/7475399/33309776-6641edf4-d430-11e7-91f0-d6f90eb5e421.png)
The existing delete button on the Job Scoring / JSON upload page should only delete the JSON and applied scoring. Currently it deletes the Job.

The delete button on the Results page should delete the CSV response data that has been uploaded for that Job. The CSV’s we get out of SurveyMonkey are cumulative, so we’re able to recover the data by uploading a fresh one. This delete button will be needed in case we accidentally upload a CSV to the wrong Job.
![image](https://user-images.githubusercontent.com/7475399/33309791-7931ddde-d430-11e7-820d-d0ea573343fd.png)

**Comment by sermolenko-bmt** [comment]
3 - 5 hour

**Comment by sermolenko-bmt** [comment]
via Hubstaff
User: Semyon Ermolenko

Project: Hirefy-client - https://app.hubstaff.com/projects/300615
Date Range: 11/29/17 - 11/29/17
Work session total: 1:23:05

Grand total: 1:23:05

**Comment by sermolenko-bmt** [comment]
via Hubstaff
User: Semyon Ermolenko

Project: Hirefy-client - https://app.hubstaff.com/projects/300615
Date Range: 11/30/17 - 11/30/17
Work session total: 2:48:30

Grand total: 4:11:35

**Comment by sermolenko-bmt** [comment]
via Hubstaff
User: Semyon Ermolenko

Project: Hirefy-client - https://app.hubstaff.com/projects/300615
Date Range: 12/04/17 - 12/04/17
Work session total: 0:52:10

Grand total: 5:03:45

**Comment by sermolenko-bmt** [comment]
via Hubstaff
User: Semyon Ermolenko

Project: Hirefy-client - https://app.hubstaff.com/projects/300615
Date Range: 12/05/17 - 12/05/17
Work session total: 0:44:25

Grand total: 5:48:10
