### ISSUE TITLE
Maximum Score, and Score Weight %

### ISSUE THREAD

**Issue by zaikin-andrew** [BestMood-Tech/Hirefy-client#37]
On the Job Scoring page, we’d like to add some additional information once a JSON is uploaded.

We’d like to see an indicator of the Maximum Score available for the ‘Basic’, ‘Skills’, and ‘Cultural’ categories. These will operate like counters as we adjust the score.
![image](https://user-images.githubusercontent.com/7475399/33309826-93cbc6c8-d430-11e7-83e3-933317fd9e38.png)

Some of the categories are more important than others when we’re determining the right candidate.

The ‘Basic’ category is essentially pre-requisites regarding location, salary, education etc. It’s more important to the overall score to know whether a candidate has the right ‘Basic’ fit for a role than the other categories. The candidate’s ‘Skills’ should be the next most important thing, followed by the candidates ‘Cultural’ fit.

Therefore, we’d like to be able to adjust the percentage weight that the score in each of these categories has on the overall score for each candidate.
The “% Weight Overall” should allow us to adjust the weight mix for each of the categories.

Example:
In the example on the screenshot the maximum scores available for each category based on the scoring for this job so far are:
Basic – 12
Skills – 30
Cultural – 12
TOTAL - 54

We want the weights to apply as follows: 
Basic – 60%
Skills – 35%
Cultural – 15%

Therefore, if imaginary candidate Tracy gets a score of: 
Basic – 11 / 12
Skills – 28 / 30
Cultural – 10 / 12
**TOTAL – 49/54**

Her candidate profile will show her percentage for each category: 
Basic fit = 92%
Skills fit = 93%
Cultural fit = 83%

But her adjusted total will be: 
Basic = 55.2
Skills = 27.9
Cultural = 9.9
TOTAL = **93% Match for the Role** _(instead of the 91% she would have gotten for 49/54)_

Compare that to imaginary candidate Fred, who lives overseas and so has a much lower Basic score:
Basic – 5 / 12 
Skills – 29 / 30 
Cultural – 10 / 12 
**TOTAL – 44/54** 

His candidate profile will show his percentage for each category as follows: 
Basic fit = 42%
Skills fit = 97%
Cultural fit = 83%

His adjusted total out of 100 will be: 
Basic = 25.2
Skills = 33.9
Cultural = 9.9
TOTAL = **69% Match for the Role** _(instead of the 81% he would have gotten for 44/54)_

The ‘% Weight Overall’ adjustments will allow us to experiment with different scoring weights. It makes sense to me that we would make these adjustments on the Job Scoring screen and then be able to see the adjusted percentage totals on the Job Report page when it refreshes.

**Comment by sermolenko-bmt** [comment]
2 - 4 hour

**Comment by sermolenko-bmt** [comment]
via Hubstaff
User: Semyon Ermolenko

Project: Hirefy-client - https://app.hubstaff.com/projects/300615
Date Range: 11/28/17 - 11/28/17
Work session total: 0:32:07

Grand total: 0:32:07

**Comment by zaikin-andrew** [comment]
Correct math - 

Basic maxes - 12 and 60%(or 0.6)
Skills maxes - 30 and 30%(or 0.3)
Cultural maxes - 12 and 10%(or 0.1)
Total - 54 and 100%(or 1)

Tracy
Basic - 11/12 = 92%
Skills - 28/30 = 93%
Cultural - 10/12 = 83%
Total = 91%

Weight adjustment
Basic - 92х0.6 = 55.2%
Skills - 93x0.3 = 27.9%
Cultural - 83x0.1 = 8.3%

Adjusted total = 91.4%

Fred 
Basic - 5/12 = 42%
Skills - 29/30 = 97%
Cultural - 10/12 = 83%
Total = 81%

Weight adjustment
Basic - 42х0.6 = 25.2%
Skills - 97x0.3 = 29.1%
Cultural - 83x0.1 = 8.3%

Adjusted total = 62.6%

**Comment by sermolenko-bmt** [comment]
via Hubstaff
User: Semyon Ermolenko

Project: Hirefy-client - https://app.hubstaff.com/projects/300615
Date Range: 12/04/17 - 12/04/17
Work session total: 1:11:02

Grand total: 1:43:09

**Comment by sermolenko-bmt** [comment]
via Hubstaff
User: Semyon Ermolenko

Project: Hirefy-client - https://app.hubstaff.com/projects/300615
Date Range: 12/05/17 - 12/05/17
Work session total: 2:42:42

Grand total: 4:25:51
