### ISSUE TITLE
Category Scores on the Job Report Page

### ISSUE THREAD

**Issue by zaikin-andrew** [BestMood-Tech/Hirefy-client#38]
Per the scoring demonstrated above, we’d also like to be able to see the individual category scores for each candidate on the Job Report page.

The ‘Score’ column should still be the normal total score.
The ‘Percent’ column displayed should be the adjusted percentage match for the role, based on the weighting described above.
![image](https://user-images.githubusercontent.com/7475399/33310061-699286d4-d431-11e7-80af-1218ed1c3f92.png)
Make an analysis: 
- prepare data on the server side and return just data for this table if we don't have this data in the cache already
- reduce the size of downloadable data and calculate ranks and other numbers on the client side

In the result, we have to understand which approach would be more suitable for our goal - Report table and Candidate profile page should work as faster as it able to do(almost instantly)

**Comment by sermolenko-bmt** [comment]
1 - 2 hour

**Comment by sermolenko-bmt** [comment]
via Hubstaff
User: Semyon Ermolenko

Project: Hirefy-client - https://app.hubstaff.com/projects/300615
Date Range: 12/05/17 - 12/05/17
Work session total: 0:00:33

Grand total: 0:00:33

**Comment by oskvortsov-bmt** [comment]
via Hubstaff
User: Oleg Skvortsov

Project: Hirefy-client - https://app.hubstaff.com/projects/300615
Date Range: 12/06/17 - 12/06/17
Work session total: 0:16:04

Grand total: 9:28:01

**Comment by sermolenko-bmt** [comment]
via Hubstaff
User: Semyon Ermolenko

Project: Hirefy-client - https://app.hubstaff.com/projects/300615
Date Range: 12/06/17 - 12/06/17
Work session total: 9:11:24

Grand total: 9:28:01
