### ISSUE TITLE
Sortable Skills on Candidate Profile

### ISSUE THREAD

**Issue by zaikin-andrew** [BestMood-Tech/Hirefy-client#39]
We’d like to make the skills answers on the Candidate Profile able to be sorted in ascending / descending order by both number (based on the question order) and the rating the candidate has given themselves, via the column headings. This will make it easier for customer review.
![image](https://user-images.githubusercontent.com/7475399/33310105-80f5a7e8-d431-11e7-865e-aa166364efa5.png)

**Comment by sermolenko-bmt** [comment]
1 -2 hour

**Comment by sermolenko-bmt** [comment]
via Hubstaff
User: Semyon Ermolenko

Project: Hirefy-client - https://app.hubstaff.com/projects/300615
Date Range: 12/03/17 - 12/03/17
Work session total: 1:16:37

Grand total: 1:16:37
