### ISSUE TITLE
Jobs page

### ISSUE THREAD

**Issue by zaikin-andrew** [BestMood-Tech/Hirefy-client#4]
- add layout and base styles
- add forms

**Comment by sermolenko-bmt** [comment]
1.5 - 3 hour

**Comment by sermolenko-bmt** [comment]
via Hubstaff
User: Semyon Ermolenko

Project: Hirefy-client - https://app.hubstaff.com/projects/300615
Date Range: 10/23/17 - 10/23/17
Work session total: 2:21:26

Grand total: 2:21:26
