### ISSUE TITLE
Job scoring editor

### ISSUE THREAD

**Issue by zaikin-andrew** [BestMood-Tech/Hirefy-client#5]
- add layout and base styles
- add form

**Comment by sermolenko-bmt** [comment]
2 - 4 hour

**Comment by sermolenko-bmt** [comment]
via Hubstaff
User: Semyon Ermolenko

Project: Hirefy-client - https://app.hubstaff.com/projects/300615
Date Range: 10/23/17 - 10/23/17
Work session total: 0:22:32

Grand total: 0:22:32

**Comment by sermolenko-bmt** [comment]
via Hubstaff
User: Semyon Ermolenko

Project: Hirefy-client - https://app.hubstaff.com/projects/300615
Date Range: 10/24/17 - 10/24/17
Work session total: 3:03:20

Grand total: 3:25:52
