### ISSUE TITLE
Adjustments for users and admin console 

### ISSUE THREAD

**Issue by zaikin-andrew** [BestMood-Tech/Hirefy-client#54]
A couple of tasks I was hoping we can take a look at when you have a sec...

The plan was to do the customer accounts next, but based on our discussion above I thought first we should tweak a couple of things in the admin console for more effective management of the customer accounts.

I'd like to make a couple of changes to the UI, and also on the back end - per your recommendations we'll separate out the treatment of the Customer (being the Company) and the users...
When we add a 'Customer' in the admin console, we will just add company information per this updated screen. Look at slack. 

No need to add a contact or contact email at that stage... once we go in to the customer dashboard we have the ability to be able to edit the company info, and also edit users, per the following updated screen. Look at the slack. 
For our admin console, when we hit edit on the customer, we should be able to edit all fields except for the Customer ID.

When we edit users, we should get a pop up allowing us to add / remove / edit the following attributes:
First Name, Last Name, Email, Password
The email will be the username for each user to logon.

**Comment by sermolenko-bmt** [comment]
via Hubstaff
User: Semyon Ermolenko

Project: Hirefy-client - https://app.hubstaff.com/projects/300615
Date Range: 12/20/17 - 12/20/17
Work session total: 6:45:34

Grand total: 6:45:34

**Comment by sermolenko-bmt** [comment]
via Hubstaff
User: Semyon Ermolenko

Project: Hirefy-client - https://app.hubstaff.com/projects/300615
Date Range: 12/21/17 - 12/22/17
Work session total: 7:18:13

Grand total: 14:03:47

**Comment by sermolenko-bmt** [comment]
via Hubstaff
User: Semyon Ermolenko

Project: Hirefy-client - https://app.hubstaff.com/projects/300615
Date Range: 12/22/17 - 12/22/17
Work session total: 2:49:33

Grand total: 16:53:20

**Comment by sermolenko-bmt** [comment]
via Hubstaff
User: Semyon Ermolenko

Project: Hirefy-client - https://app.hubstaff.com/projects/300615
Date Range: 12/23/17 - 12/23/17
Work session total: 1:25:42

Grand total: 18:19:02
