### ISSUE TITLE
Sub domain and ec2 instance. 

### ISSUE THREAD

**Issue by zaikin-andrew** [BestMood-Tech/Hirefy-client#55]
The other small thing I'd like to get done is to get the sub-domain http://app.hirefy.me  set up for access to the app.  DNS management is via Bluehost....

**Comment by sermolenko-bmt** [comment]
via Hubstaff
User: Semyon Ermolenko

Project: Hirefy-client - https://app.hubstaff.com/projects/300615
Date Range: 12/23/17 - 12/23/17
Work session total: 1:22:02

Grand total: 1:22:02
