### ISSUE TITLE
Job results

### ISSUE THREAD

**Issue by zaikin-andrew** [BestMood-Tech/Hirefy-client#6]
- add layout and base styles
- add form
- add ag-grid for the table

**Comment by sermolenko-bmt** [comment]
1 - 3 hour

**Comment by sermolenko-bmt** [comment]
via Hubstaff
User: Semyon Ermolenko

Project: Hirefy-client - https://app.hubstaff.com/projects/300615
Date Range: 10/24/17 - 10/25/17
Work session total: 1:08:26

Grand total: 1:08:26

**Comment by sermolenko-bmt** [comment]
via Hubstaff
User: Semyon Ermolenko

Project: Hirefy-client - https://app.hubstaff.com/projects/300615
Date Range: 10/25/17 - 10/25/17
Work session total: 1:01:14

Grand total: 2:09:40
