### ISSUE TITLE
Rds

### ISSUE THREAD

**Issue by sermolenko-bmt** [BestMood-Tech/Hirefy-client#66]
- create RDS
- set up RDS

lead time - about 1 - 1.5 hours

**Comment by sermolenko-bmt** [comment]
via Hubstaff
User: Semyon Ermolenko

Project: Hirefy-client - https://app.hubstaff.com/projects/300615
Date Range: 01/18/18 - 01/19/18
Work session total: 1:01:51

Grand total: 1:01:51

**Comment by zaikin-andrew** [comment]
Add backups for production

**Comment by sermolenko-bmt** [comment]
via Hubstaff
User: Semyon Ermolenko

Project: Hirefy-client - https://app.hubstaff.com/projects/300615
Date Range: 02/11/18 - 02/11/18
Work session total: 1:27:39

Grand total: 2:29:30
