### ISSUE TITLE
Job report viewer

### ISSUE THREAD

**Issue by zaikin-andrew** [BestMood-Tech/Hirefy-client#7]
- add layout and base styles

**Comment by sermolenko-bmt** [comment]
0.5 - 1 hour

**Comment by sermolenko-bmt** [comment]
via Hubstaff
User: Semyon Ermolenko

Project: Hirefy-client - https://app.hubstaff.com/projects/300615
Date Range: 10/24/17 - 10/24/17
Work session total: 0:13:09

Grand total: 0:13:09
