### ISSUE TITLE
Several changes

### ISSUE THREAD

**Issue by zaikin-andrew** [BestMood-Tech/Hirefy-client#82]
A couple of other items though. All relatively small I think.

CUSTOMER ACCOUNT
- need to be able to view completed jobs data
- dis-like doesn't work now... was working before
- when going forward / back through filtered list of Favorite applicants it includes all - possible to only scroll through favorites when filtered?

ADMIN ACCOUNT
- weird app refresh when changing score weight
- possible to get like / dislike indicator in candidate profile headers as well?

**Comment by sermolenko-bmt** [comment]
via Hubstaff
User: Semyon Ermolenko

Project: Hirefy-client - https://app.hubstaff.com/projects/300615
Date Range: 01/29/18 - 01/29/18
Work session total: 1:19:30

Grand total: 1:19:30
