### ISSUE TITLE
Research. Job creation automatisation 

### ISSUE THREAD

**Issue by zaikin-andrew** [BestMood-Tech/Hirefy-client#88]
We’ve got the basic “job scoring and reporting” part of the app up and running, but now we’d like to get the “job creation” part sorted out so that customers are able to control that themselves, and we’re able to get applications directly, instead of customers having to send us names & emails.

An employer survey to create a ‘job profile’. The survey will need to include logic that determines the next question based on the previous response for some parts. The employer survey answers will create a profile which we can use to manually (at this stage) create our applicant surveys and scoring matrix for responses.

**Comment by oskvortsov-bmt** [comment]
via Hubstaff
User: Oleg Skvortsov

Project: Hirefy-client - https://app.hubstaff.com/projects/300615
Date Range: 02/12/18 - 02/12/18
Work session total: 3:16:28

Grand total: 3:16:28

**Comment by oskvortsov-bmt** [comment]
via Hubstaff
User: Oleg Skvortsov

Project: Hirefy-client - https://app.hubstaff.com/projects/300615
Date Range: 02/13/18 - 02/13/18
Work session total: 3:12:36

Grand total: 6:29:04

**Comment by oskvortsov-bmt** [comment]
via Hubstaff
User: Oleg Skvortsov

Project: Hirefy-client - https://app.hubstaff.com/projects/300615
Date Range: 02/20/18 - 02/20/18
Work session total: 1:36:06

Grand total: 8:05:10
