### ISSUE TITLE
Different fixes

### ISSUE THREAD

**Issue by zaikin-andrew** [BestMood-Tech/Hirefy-client#90]
Look at the milestone pdf for the full description
- Colours
- Percentage Match Graphic
- Phone Numbers
- Support Contact Details

**Comment by oskvortsov-bmt** [comment]
via Hubstaff
User: Oleg Skvortsov

Project: Hirefy-client - https://app.hubstaff.com/projects/300615
Date Range: 02/13/18 - 02/13/18
Work session total: 1:16:56

Grand total: 1:16:56

**Comment by oskvortsov-bmt** [comment]
via Hubstaff
User: Oleg Skvortsov

Project: Hirefy-client - https://app.hubstaff.com/projects/300615
Date Range: 02/14/18 - 02/14/18
Work session total: 3:16:04

Grand total: 4:33:00
